## publishable areas
"area: core":
  - changed-files:
      - any-glob-to-any-file: "bamboozle/**"

## non-publishable areas
"area: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - ".assets/**"
          - "README.md"
          - "llm.txt"
          - "LICENSE-APACHE"
          - "LICENSE-MIT"

"area: ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "scripts/**"

"area: examples":
  - changed-files:
      - any-glob-to-any-file: "examples/**"
