routes:
#http://localhost:18080/multi-route/item1/item2/item3
  - match:
      verb: GET
      pattern: multi-route/{part1?}/{part2?}/{part3?}
    response:
      status: "{% if routeValues.part1 != blank %}200{% else %}400{% endif %}"
      headers:
        Content-Type: "application/json"
      content: |
        [
          {% for kvp in routeValues %} 
            "{{kvp[0]}}={{kvp[1]}}"{% unless forloop.last %}, {% endunless %}
          {% endfor %}
        ]