services:
  bamboozle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
      - "19090:9090"
    volumes:
      - ./test-configs:/test-configs
    environment:
      - ROUTE_CONFIG_THROW_ON_ERROR=true
      - ROUTE_CONFIG_FOLDERS=["/test-configs"]