name: CI

on:
  pull_request:
    types: [opened, synchronize]
  workflow_call:

jobs:
  rust-test:
    name: Rust Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: RUSTFLAGS="-D warnings" cargo test --manifest-path bamboozle/Cargo.toml
