name: DOTNET Release

on:
  push:
    tags:
      - 'sdks/dotnet/v*.*.*'

jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Extract Version
        id: extract_version
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#sdks/dotnet/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Pack
        run: dotnet pack ./sdks/dotnet/Bamboozle/Bamboozle.Core/Bamboozle.Core.csproj --configuration Release -p:PackageVersion=${{ steps.extract_version.outputs.version }}

      - name: Publish to NuGet
        run: dotnet nuget push ./sdks/dotnet/Bamboozle/Bamboozle.Core/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
