name: Example - Azure KeyVault tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  azure-keyvault-example:
    name: Azure KeyVault Example
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x"

      - name: Run azure-keyvault example
        run: bash examples/azure-keyvault/runme.sh
