name: PR - dotnet unit tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [main]
    paths:
      - "sdks/dotnet/**"
      - ".github/workflows/pr-test-dotnet.yml"

env:
  DOTNET_VERSION: "10.x"

jobs:
  dotnet-unit-test:
    name: Build & Test dotnet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Run Bamboozle Docker
        run: docker compose -f ./scripts/docker-compose.dev.yml up -d

      - name: Test
        run: dotnet test ./sdks/dotnet/Bamboozle/Bamboozle.slnx --configuration Release --logger "GitHubActions"
