name: Publish - dotnet

on:
  push:
    tags:
      - "sdks/dotnet/v*.*.*"

jobs:
  unit-tests:
    permissions:
      contents: read
    uses: ./.github/workflows/pr-test-dotnet.yml

  dotnet-publish:
    needs: unit-tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x"

      - name: Extract Version
        id: extract_version
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#sdks/dotnet/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build & pack
        run: |
          dotnet pack ./sdks/dotnet/Bamboozle/Bamboozle.Core/Bamboozle.Core.csproj \
            --configuration Release \
            -p:PackageVersion=${{ steps.extract_version.outputs.version }}

      - name: NuGet login
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ vars.NUGET_USERNAME }}

      - name: Push to NuGet.org
        run: |
          dotnet nuget push ./sdks/dotnet/Bamboozle/Bamboozle.Core/bin/Release/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}

  create-release:
    needs: [dotnet-publish]
    permissions:
      contents: write
      pull-requests: read
    uses: ./.github/workflows/reusable-create-release.yml
    with:
      tag: ${{ github.ref_name }}
      area_labels: "area: sdks/dotnet"
      make_latest: false
      prerelease: false
