name: Publish - npm

on:
  push:
    tags:
      - "sdks/npm/v*"

permissions:
  contents: read

jobs:
  playwright-tests:
    uses: ./.github/workflows/pr-test-playwright.yml

  publish-npm:
    needs: playwright-tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Extract Version
        id: extract_version
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#sdks/npm/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: ./sdks/npm
        run: npm ci

      - name: Set Version
        working-directory: ./sdks/npm
        run: npm version ${{ steps.extract_version.outputs.version }} --no-git-tag-version

      - name: Run tests
        working-directory: ./sdks/npm
        run: npm run test

      - name: Publish to NPM
        working-directory: ./sdks/npm
        # Note: npm run build is triggered automatically by the prepublishOnly script
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: [publish-npm]
    permissions:
      contents: write
      pull-requests: read
    uses: ./.github/workflows/reusable-create-release.yml
    with:
      tag: ${{ github.ref_name }}
      area_labels: "area: sdks/npm"
      make_latest: false
      prerelease: false
