name: Startup Time

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  startup-time:
    name: Docker Startup Time
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build image
        run: docker compose -f ./scripts/docker-compose.dev.yml up -d

      - name: Run startup time test
        run: bash ./scripts/perf-test/test-startup.sh bamboozle:dev 5
